Keep the orgin function still, add new SIGUSR1 to stop recording only

diff --git a/src/giph b/src/giph
--- a/src/giph
+++ b/src/giph
@@ -2,6 +2,25 @@
 
 stty -echoctl # don't print ^C when pressing ctrl+c
 
+function handle_usr1(){
+  if [[ $FFMPEG_PID ]]; then
+    kill -int "$FFMPEG_PID"
+    FFMPEG_PID=""
+
+    wait
+
+    [ "$?" = 1 ] && log_error "recording video with ffmpeg failed"
+    log "completed ffmpeg video recording" 1 true
+
+    convert
+    wait
+
+    exit
+  fi
+}
+
+trap handle_usr1 SIGUSR1
+
 readonly VERSION=1.1.1
 
 # verbosity
@@ -49,6 +68,7 @@ OPTIONS
   -ms, --microphone-source=STRING   Overwrite the default microphone source.
   -y,  --notify                     Send notification on error or success.
        --stop                       Finish any running giph recordings.
+       --finish                     Finish any screen recordings only.
 
 SLOP OPTIONS
   -b, --bordersize=FLOAT                Set the selection border thickness.
@@ -129,6 +149,9 @@ while [[ "$1" == -* ]]; do
     ;;
   --stop)
     SHOULD_STOP=true
+    ;;
+  --finish)
+    SHOULD_FINISH=true
     ;;
   -s|--select)
     SLOP=1
@@ -454,11 +477,13 @@ function delete_temporary_directory() {
   log "deleted temporary directory $TEMP_DIRECTORY" 2 true
 }
 
-function giph() {
+function prepare() {
   get_geometry
   create_temporary_directory
   record
+}
 
+function convert() {
   if [[ "$FORMAT" == "gif" || "$FORMAT" == "webm" ]]; then
     encode
   fi
@@ -467,22 +492,37 @@ function giph() {
 
   delete_temporary_directory
   exit 0
+
 }
+function giph() {
+  prepare
+  convert
+}
+
 
 function stop_all_recordings() {
   for pid in $(pgrep -f "bash.+giph"); do
     if [ $pid -eq $$ ]; then
       continue
     fi
-    record_pid=$(pgrep -P $pid -f "ffmpeg -f x11grab")
-    if [ -n "$record_pid" ]; then
-      kill -INT $record_pid
+    kill -INT -$pid
+  done
+}
+
+
+function stop_recording_only() {
+  for pid in $(pgrep -f "bash.+giph"); do
+    if [ "$pid" -eq $$ ]; then
+      continue
     fi
+    kill -USR1 $pid
   done
 }
 
 if [ -n "$SHOULD_STOP" ]; then
   stop_all_recordings
+elif [ -n "$SHOULD_FINISH" ]; then
+  stop_recording_only
 else
   giph
 fi
